### ISSUE TITLE
Richtextview begin{align} not working.

### ISSUE THREAD

**Issue by kalathiyanilesh1** [tophat/RichTextView#101]
How can i show this LaTex string in RichtextView?

"\\begin{align}
\n\\because \\text{According to the question,}\\\\
\n\\frac{1}{2}m(v_f)^2&=\\frac{1}{2}\\times\\frac{1}{2}m(v_i)^2\\\\
\n(v_i,v_f=\\text{initial and final speeds of the body}\\\\
\nor \\quad\\ (v_f)^2&=\\frac{(v_i)^2}{2}\\ or\\  v_f=\\frac{10}{\\sqrt{2}}\\\\
\nGiven,\\quad f&=-kv\\\\
\nor\\quad ma&=-kv\\Rightarrow\\frac{mdv}{dt}=-kv\\\\
\n\\Rightarrow\\int_{10}^{\\frac{10}{\\sqrt{2}}}\\frac{1}{v}dv&=-\\int_{0}^{10}kdt\\tag{ m=1kg}\\\\
\n\\Rightarrow(ln\\ v)_{10}^{\\frac{10}{\\sqrt{2}}}&=-k(10)\\\\
\n\\Rightarrow ln\\ \\frac{10}{\\sqrt{2}} - ln\\ 10&=-k(10)\\\\
\n\\Rightarrow k=\\frac{1}{10}ln\\frac{10}{10/\\sqrt{2}}&=\\frac{1}{10}ln \\sqrt{2}=\\frac{ln\\ 2}{20}
\n
\n\\end{align}"

**Comment by aelkady** [comment]
I am going to close this because this is a limitation of `iosMath` - some LaTeX syntax does not work properly. You need to file a bug report with https://github.com/kostub/iosMath. Thanks!
