### ISSUE TITLE
Use AST HTML parsing available in latest Down library

### ISSUE THREAD

**Issue by aelkady** [tophat/RichTextView#103]
## What is the purpose of your *issue*?
- [x] Feature Request
- [ ] Question
- [ ] Other

## Description
Down has recently updated to use AST parsing to generate an `NSAttributedString` from HTML instead of the usual `NSAttributedString` way of doing it. However, this has broken some tests and functionality in this library. The purpose of this ticket is to update to the latest `Down` library and fix anything that's broken.

**Comment by BisuGit** [comment]
This issue is no longer applicable because we moved away from Down HTML parsing.
