### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by mm623645699** [tophat/RichTextView#104]
Build system information
error: /Users/maming/Desktop/xcode/HandMadeSoup/Carthage/Checkouts/RichTextView/Pods/Target Support Files/Pods-RichTextView/Pods-RichTextView.release.xcconfig: unable to open file (in target "RichTextView" in project "RichTextView") (in target 'RichTextView')

**Comment by aelkady** [comment]
@mm623645699 sorry for getting to this so late - can you post screenshots on what is going on?
Did you also try the usual clean project, restart XCode? Below is also an issue for someone who went through this before:
https://github.com/tophat/RichTextView/issues/94

**Comment by aelkady** [comment]
@mm623645699 the project works fine for me locally, and this issue is almost three months old, so I will be closing it. If it is still not fixed for you please feel free to reopen with more details so I can take a second look. Thanks! 😄
