### ISSUE TITLE
Add Gesture Recognizer

### ISSUE THREAD

**Issue by Franklin098** [tophat/RichTextView#107]
I want to know how can I add a GestureRecognizer to a RichTextView object that is nested inside another UIView. Thank you.

**Comment by aelkady** [comment]
Hey @Franklin098 you can do the following:
```
let richTextView = RichTextView()
richTextView.addGestureRecognizer(// your gesture recognizer)
```
let me know if this doesn't work

**Comment by aelkady** [comment]
@Franklin098 given that this issue is 2 months old and the above code snippet works for me I will be closing this issue. If you feel otherwise please feel free to re-open this issue with more details on what about the code snippet above isn't working. Thanks 😄
