### ISSUE TITLE
String index is out of bounds

### ISSUE THREAD

**Issue by deepakverma4** [tophat/RichTextView#118]
recent release is crashing.
File name: ```StringExtension.swift```
 i've attached the snapshot.
![Screenshot 2019-09-20 at 4 37 45 PM](https://user-images.githubusercontent.com/31440793/65322731-3eca5b00-dbc5-11e9-8c99-2b1e9fe0feed.png)

**Comment by aelkady** [comment]
@deepakverma4 I have opened https://github.com/tophat/RichTextView/pull/119 to mitigate this - I will let you know once the Pod has been updated and you can check and verify

**Comment by aelkady** [comment]
@deepakverma4 this should be fixed in v2.3.5 of the Pod - I will close this issue but feel free to reopen if the crash still persists!
