### ISSUE TITLE
Fraction rendering problem

### ISSUE THREAD

**Issue by Fateh-Alam** [tophat/RichTextView#172]
Whenever I am trying to render a fraction by writing LaTex code, It is giving me the following error:  

"Invalid escape sequence in literal"

`struct latex: View {`
    `@State var string = "[math]F=\frac{m}{a}[/math]"`
   ` var body: some View {`
      `  TextView(string: $string)`
  `  }`
`}`

**Comment by noahnu** [comment]
You need to escape the backslash:

```
var string = "[math]F=\\frac{m}{a}[/math]"
```

**Comment by Fateh-Alam** [comment]
Thanks for solving my problem!
