### ISSUE TITLE
the baseline of the text is always on the bottom, could you make it codable?

### ISSUE THREAD

**Issue by BraverChiang** [tophat/RichTextView#83]
## What is the purpose of your *issue*?
- [ ] Feature: make the baseline/alignment of the text codable

## Description
when I put a some normal text and big math formula at the same line. The baseline is at the bottom of the textview, so the formula looks too tall *&^%, that looks weird.
I hope the baseline stand in the center or make it codable

**Comment by aelkady** [comment]
@BraverChiang that sounds like a great idea. Have you already started working on a solution for this?

**Comment by aelkady** [comment]
@BraverChiang I have opened a PR above if you would like to take a look.

**Comment by aelkady** [comment]
This is now fixed in 1.0.8
