### ISSUE TITLE
Add RichTextView input callback

### ISSUE THREAD

**Issue by HaidyCao** [tophat/RichTextView#88]
## What is the purpose of your *issue*?
- [x] Feature Request
- [ ] Question
- [ ] Other

## Description
Provide as much information possible about the issue below
I want listen content of the RichTextView when input or delete some content.

**Comment by aelkady** [comment]
@HaidyCao could you elaborate more on this? Are you essentially saying that you want to be hooked up to the delegate methods of the `UITextView` subviews in the `RichTextView`?

**Comment by HaidyCao** [comment]
Thank you. But I need to get the child of `RichTextView ` as  `UITextView `  and hook the delegate of that.

**Comment by aelkady** [comment]
@HaidyCao I have opened https://github.com/tophat/RichTextView/pull/91 to address this issue, feel free to take a look and make any changes if you feel it's necessary.
