### ISSUE TITLE
How to import RichTextView?

### ISSUE THREAD

**Issue by kalathiyanilesh1** [tophat/RichTextView#94]
import RichTextView showing error like No such module 'RichTextView'

already add pod pod 'RichTextView'

**Comment by aelkady** [comment]
Hey @kalathiyanilesh1 have you done a `pod install --repo-update` as well after updating your `Podfile`?

**Comment by aelkady** [comment]
Also you need to make sure you are working with the `xcworkspace` file not the `xcodeproj` file

**Comment by kalathiyanilesh1** [comment]
yes I'm working on xcworkspace file not the xcodeproj file, still not solved this issue
![Screenshot 2019-04-30 at 6 11 46 PM](https://user-images.githubusercontent.com/27014642/56962153-7af81300-6b73-11e9-8156-159d5a8a8afc.png)

**Comment by aelkady** [comment]
Can you try doing a clean build to see if this fixes the problem? If not can you open the example project (in the `Example` directory in the repo) and see if that is also broken for you?

**Comment by kalathiyanilesh1** [comment]
here is my project link "https://we.tl/t-DiJt67R9Fn", check it

**Comment by aelkady** [comment]
Can you try changing the deployment target of RichTextView to iOS 10 (see screenshot attached)? Let me know if this fixes your issue.
<img width="1150" alt="Screen Shot 2019-04-30 at 8 50 00 AM" src="https://user-images.githubusercontent.com/6837609/56962608-ff6f7500-6b24-11e9-910d-d7e00da3af88.png">

**Comment by kalathiyanilesh1** [comment]
hello @aelkady , not working this solution. can you pls check my demo app & try to resolve this issue

**Comment by aelkady** [comment]
@kalathiyanilesh1 the screenshot I sent above is from the project you sent me - outside of cleaning your `DerivedData` folder and doing a clean build there is not much else I can recommend, changing the deployment on the `RichTextView` framework made the project build successfully for me

**Comment by kalathiyanilesh1** [comment]
Hello @aelkady , Solved my issue by setup this

![Screenshot 2019-04-30 at 6 25 57 PM](https://user-images.githubusercontent.com/27014642/56962995-7cc2d600-6b75-11e9-85d2-3a58e999034a.png)
![Screenshot 2019-04-30 at 6 26 03 PM](https://user-images.githubusercontent.com/27014642/56962996-7cc2d600-6b75-11e9-8a4b-3f086eeda281.png)

**Comment by kalathiyanilesh1** [comment]
@aelkady , Thanks for your support.

**Comment by aelkady** [comment]
No worries, closing the issue and might open a PR soon to update the deployment target. The problem was that SnapKit has a minimum deployment of iOS 10.0 and that is a dependency of RichTextView.
