### ISSUE TITLE
RichTextView inside CollectionViewCell

### ISSUE THREAD

**Issue by deepakverma4** [tophat/RichTextView#99]
## What is the purpose of your *issue*?

- [x] Bug
- [ ] Question
- [ ] Other

## Description
I am beginner to swift programming.
I am trying to use richtextview inside uicollectionview cell. My collectionview cell contain one richtextview and one imageview both embedded in a stackview. 
But the problem i am facing is as soon as collectionview cell loads all cells disappears and i can only see the scroll indicator.

Edit: If I update input inside ```cellForItemAt``` only then this happens.

**Comment by aelkady** [comment]
You may need to set a custom height for the collection view cell. You can get the custom height by doing:
```
let inputText = "Test input"
let font = UIFont.testFont
let textView = RichTextView(frame: .zero)
textView.update(input: inputText, font: font)
textView.snp.makeConstraints { make -> Void in
    make.width.equalTo(width)
}
return textView.systemLayoutSizeFitting(UIView.layoutFittingExpandedSize).height
```
Can you try and see if this works?

**Comment by deepakverma4** [comment]
@aehlke yes it worked. 
But another issue i'm facing is `didSelectItemAt` is not called when i click on richtextview. also if i add tapgesture recogniser to richtextview the selector is not called.
Can you please help me in this?

**Comment by aelkady** [comment]
@deepakverma4 you may have to make the rich text view not selectable as well, so that the UITextView in RichTextView does not capture any of the touches (initializing with isSelectable being false). Can you try that as well?

**Comment by deepakverma4** [comment]
@aelkady not it's not working :(

**Comment by deepakverma4** [comment]
Finally resolved it by setting ```richView.isUserInteractionEnabled = false```
